### ISSUE TITLE
如何解决插件安装后返回的错误和更新chatgpt-on-wechat

### ISSUE THREAD

**Issue by MILKMILKKING** [fatwang2/sum4all#2]
你好，我卸载了原先的插件，安装好了新的插件。并且填入了key。
但是返回以下错误：
[ERROR][2023-09-24 22:32:30][chat_channel.py:280] - Worker return exception: SHARING
Traceback (most recent call last):
  File "C:\Users\lyri_1335282\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chatgpt-on-wechat\channel\chat_channel.py", line 155, in _handle
    reply = self._generate_reply(context)
  File "D:\chatgpt-on-wechat\channel\chat_channel.py", line 165, in _generate_reply
    e_context = PluginManager().emit_event(
  File "D:\chatgpt-on-wechat\plugins\plugin_manager.py", line 189, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\chatgpt-on-wechat\plugins\sum4all\sum4all.py", line 50, in on_handle_context
    if context.type == ContextType.SHARING:
  File "C:\Users\lyri_1335282\AppData\Local\Programs\Python\Python38\lib\enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: SHARING

是否因为我们没有将chatgpt-on-wechat更新到最新？
弱弱的问一下，我应该如何更新chatgpt-on-wechat？

**Comment by MILKMILKKING** [comment]
是chatgpt-on-wechat没有更新的问题。更新后可以总结链接，但依然无法总结卡片。
