### ISSUE TITLE
url总结能否增加链接关键词黑白名单？比如发给机器人的群聊邀请也总结了，然后跟系统的pass指令冲突了导致卡住

### ISSUE THREAD

**Issue by spacex-3** [fatwang2/sum4all#84]
[INFO][2024-09-02 14:52:07][sum4all.py:252] - [sum4all] Summary URL : https://support.weixin.qq.com/cgi-bin/mmsupport-bin/addchatroombyinvite?ticket=****
%3D%3D                                    
[INFO][2024-09-02 14:52:07][sum4all.py:256] - Updated last_url in params_cache for user.
[INFO][2024-09-02 14:52:07][sum4all.py:330] - Handling Sum4All request...
[INFO][2024-09-02 14:52:07][sum4all.py:366] - Sending request to LLM...
[INFO][2024-09-02 14:52:13][sum4all.py:370] - Received response from LLM.
[INFO][2024-09-02 14:52:13][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=📌总结  
该群聊的邀请已过期，无法再加入。

💡要点  
1. ⏰ 群聊邀请已失效，不能访问  
2. ❌ 无法参与群聊讨论  
3. 📩 可能需要重新发送邀请才能加入

💬5min内输入问+问题，可继续追问), receiver=@aca0ea34b3ee484a3b017842534aa749
[WARNING][2024-09-02 14:53:28][wechat_message.py:36] - 机器人加入群聊消息，不处理~
[WARNING][2024-09-02 14:53:28][wechat_message.py:109] - [WX]get other_user_id failed: 'NickName'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 47, in handler_group_msg
    WechatChannel().handle_group(cmsg)
  File "/root/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 65, in wrapper
    return func(self, cmsg)
           ^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 205, in handle_group
    context = self._compose_context(cmsg.ctype, cmsg.content, isgroup=True, msg=cmsg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                             [69/1678]
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 64, in _compose_context
    check_contain(group_name, group_name_keyword_white_list),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 394, in check_contain
    if content.find(ky) != -1:
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

WARNING: Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 47, in handler_group_msg
    WechatChannel().handle_group(cmsg)
  File "/root/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 65, in wrapper
    return func(self, cmsg)
           ^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 205, in handle_group
    context = self._compose_context(cmsg.ctype, cmsg.content, isgroup=True, msg=cmsg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 64, in _compose_context
    check_contain(group_name, group_name_keyword_white_list),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 394, in check_contain
    if content.find(ky) != -1:
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

[WARNING][2024-09-02 14:53:49][wechat_message.py:36] - 机器人加入群聊消息，不处理~
[WARNING][2024-09-02 14:53:49][wechat_message.py:109] - [WX]get other_user_id failed: 'NickName'
Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 47, in handler_group_msg
    WechatChannel().handle_group(cmsg)
  File "/root/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 65, in wrapper
    return func(self, cmsg)
           ^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 205, in handle_group
    context = self._compose_context(cmsg.ctype, cmsg.content, isgroup=True, msg=cmsg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 64, in _compose_context
    check_contain(group_name, group_name_keyword_white_list),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 394, in check_contain
    if content.find(ky) != -1:
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

WARNING: Traceback (most recent call last):
  File "/root/chatgpt-on-wechat/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
        ^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 47, in handler_group_msg
    WechatChannel().handle_group(cmsg)
  File "/root/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 65, in wrapper
    return func(self, cmsg)
           ^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 205, in handle_group
    context = self._compose_context(cmsg.ctype, cmsg.content, isgroup=True, msg=cmsg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 64, in _compose_context
    check_contain(group_name, group_name_keyword_white_list),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chatgpt-on-wechat/channel/chat_channel.py", line 394, in check_contain
    if content.find(ky) != -1:
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by spacex-3** [comment]
来自gpt的修复：

def on_handle_context(self, e_context: EventContext):
    context = e_context["context"]
    if context.type not in [ContextType.TEXT, ContextType.SHARING, ContextType.FILE, ContextType.IMAGE]:
        return
    msg: ChatMessage = e_context["context"]["msg"]
    user_id = msg.from_user_id
    content = context.content
    isgroup = e_context["context"].get("isgroup", False)

    url_match = re.match('https?://(?:[-\w.]|(?:%[\da-fA-F]{2}))+', content)
    unsupported_urls = re.search(
        r'.*finder\.video\.qq\.com.*|'
        r'.*support\.weixin\.qq\.com/update.*|'
        r'.*support\.weixin\.qq\.com/security.*|'
        r'.*mp\.weixin\.qq\.com/mp/waerrpage.*|'
        r'.*support\.weixin\.qq\.com/cgi-bin/mmsupport-bin/addchatroombyinvite.*',
        content
    )

    if unsupported_urls:
        # 如果匹配到不支持的链接，直接返回，不进行处理
        return

**Comment by spacex-3** [comment]
` 
        url_match = re.match(r'https?://(?!(support\.weixin\.qq\.com/cgi-bin/mmsupport-bin/addchatroombyinvite))[-\w.]+(?:%[\da-fA-F]{2})+', content)

        unsupported_urls = re.search(
            r'.*finder\.video\.qq\.com.*|'
            r'.*support\.weixin\.qq\.com/update.*|'
            r'.*support\.weixin\.qq\.com/security.*|'
            r'.*mp\.weixin\.qq\.com/mp/waerrpage.*|'
            r'.*support\.weixin\.qq\.com/cgi-bin/mmsupport-bin/addchatroombyinvite.*|'
            r'.*weibo\.com.*|'
            r'.*xiaohongshu\.com.*|'
            r'.*yangkeduo\.com.*|'
            r'.*pinduoduo\.com.*|'
            r'.*dianping\.com.*|'
            r'.*meituan\.com.*|'
            r'.*baidu\.com.*|'
            r'.*amap\.com.*|'
            r'.*taobao\.com.*|'
            r'.*tmall\.com.*',
            content
        )`
